config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  resources :restaurants, only: [:index, :new, :show, :create] do
    resources :reviews, only: [:create]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurants

  validates :name, :inclusion => { :in => ["chinese", "italian", "japanese", "french", "belgian"]}

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :category
  has_many :reviews

  validates :name, presence: true
  validates :address, presence: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurants

  validates :rating, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController


  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.create(restaurant_params)
    if restaurant.valid?
      flash[:notice] = "your restaurant is created"
      redirect_to restaurants_path
    else
      flash[:notice] = "your restaurant is NOT created : #{task.errors.messages}"
      redirect_to restaurants_path
    end
  end



  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone, :category_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    restaurant.reviews.create(review_params)
    redirect_to restaurant
  end


  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restoapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrapper">

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/restaurants">RestoApp</a>
        </div>
      </div>
    </nav>

  <div class="container">
    <%= yield %>
  </div>
</div>

   <div id="footer">
      <div class="container">
        <p class="text-muted credit">RestoApp</p>
      </div>
    </div>

</body>
</html>

app/views/restaurants/index.html.erb
<div class="jumbotron">
  <h1>Le guide des restaurants</h1>
</div>

<div class="notice">
  <%= flash[:notice] %>
</div>


<table class ="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Addresse</th>
      <th>Phone</th>
      <th>Category</th>
      <th>#Reviews</th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant_path(restaurant)%></td> <td><%= restaurant.address %></td> <td><%= restaurant.phone %></td> <td><%= restaurant.category.name %></td> <td><%=restaurant.reviews.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<%= link_to 'Add a restaurant', new_restaurant_path, class: "btn btn-primary" %>

app/views/restaurants/new.html.erb
<h1>Creer un nouveau restaurant</h1>

<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :category_id %>
  <%= f.select :category_id, {'chinese' => 1, 'italian' => 2, 'japanese' => 3, 'french' => 4, 'belgian' => 5 } %>

  <%= f.submit %>
<% end %>

<%= link_to 'Cancel', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone %></p>
<p><%= @restaurant.category.name %></p>
<p><%= @restaurant.reviews.count %></p>


<h2>Les commentaires</h2>

<ul>
  <% @restaurant.reviews.each do |review| %>
  <li><%= review.content %>  // <%= review.rating %></li>
<% end %>
</ul>


<h2>Add a commentaire</h2>
<%= form_for([@restaurant, @restaurant.reviews.build]) do |f| %>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :rating %><br>
  <%= f.select :rating, {'1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5 } %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to "retour", restaurants_path %>